name: validator-node

networks:
  pantos-validator-node:
    name: pantos-validator-node
    attachable: true
  pantos-ethereum:
    name: pantos-ethereum
    external: true

services:
  app:
    networks:
      pantos-validator-node:
      pantos-ethereum:
    entrypoint: sh -c 'set -a; . /etc/pantos/eth-data/ETHEREUM.env && . /etc/pantos/bnb-data/BNB.env; set +a; exec /usr/bin/pantos-validator-node-server'
    env_file:
      - validator-node-config.docker.env
    environment:
      APP_URL: http://app:8080
      BNB_PRIVATE_KEY: /etc/pantos/bnb-data/keystore
      ETHEREUM_PRIVATE_KEY: /etc/pantos/eth-data/keystore
    volumes:
      - type: volume
        source: bnb-data
        target: /etc/pantos/bnb-data
        read_only: true
      - type: volume
        source: eth-data
        target: /etc/pantos/eth-data
        read_only: true
  worker:
    networks:
      pantos-validator-node:
      pantos-ethereum:
    entrypoint: sh -c 'set -a; . /etc/pantos/eth-data/ETHEREUM.env && . /etc/pantos/bnb-data/BNB.env; set +a; exec /usr/bin/pantos-validator-node-celery'
    env_file:
      - validator-node-config.docker.env
    environment:
      APP_URL: http://app:8080
      BNB_PRIVATE_KEY: /etc/pantos/bnb-data/keystore
      ETHEREUM_PRIVATE_KEY: /etc/pantos/eth-data/keystore
      PANTOS_STATUS_MONITOR: 1
    ports:
      - 5555:5555
    volumes:
      - type: volume
        source: bnb-data
        target: /etc/pantos/bnb-data
        read_only: true
      - type: volume
        source: eth-data
        target: /etc/pantos/eth-data
        read_only: true

volumes:
  bnb-data:
    name: bnb-data
    external: true
  eth-data:
    name: eth-data
    external: true
