networks:
  pantos-validator-node:
  pantos-validator-node-primary:
  pantos-ethereum:
    name: pantos-ethereum-${STACK_IDENTIFIER}-${ETHEREUM_NETWORK-1}
    external: true

services:
  app:
    networks:
      pantos-validator-node:
      pantos-validator-node-primary:
      pantos-ethereum:
    entrypoint: sh -c 'set -a; . /etc/pantos/eth-data/ETHEREUM.env && . /etc/pantos/bnb-data/BNB.env; set +a; exec /usr/bin/pantos-validator-node-server'
    environment:
      PANTOS_ENV_FILE: /etc/pantos/validator-node-config.env
      APP_PRIMARY_URL: http://validator-node-${STACK_IDENTIFIER}-1:8080
      APP_URL: http://validator-node-${STACK_IDENTIFIER}-${INSTANCE-1}:8080
      BNB_PRIVATE_KEY: /etc/pantos/bnb-data/keystore
      ETHEREUM_PRIVATE_KEY: /etc/pantos/eth-data/keystore
    volumes:
      - type: volume
        source: bnb-data
        target: /etc/pantos/bnb-data
        read_only: true
      - type: volume
        source: eth-data
        target: /etc/pantos/eth-data
        read_only: true
      - type: bind
        source: ./validator-node-config.docker.env
        target: /etc/pantos/validator-node-config.env
        read_only: true
    develop:
      watch:
        - action: sync+restart
          path: validator-node-config.docker.env
          target: /root/validator-node-config.docker.env

  worker:
    networks:
      pantos-validator-node:
      pantos-validator-node-primary:
      pantos-ethereum:
    entrypoint: sh -c 'set -a; . /etc/pantos/eth-data/ETHEREUM.env && . /etc/pantos/bnb-data/BNB.env; set +a; exec /usr/bin/pantos-validator-node-celery'
    environment:
      PANTOS_ENV_FILE: /etc/pantos/validator-node-config.env
      APP_URL: http://validator-node-${STACK_IDENTIFIER}-${INSTANCE-1}:8080
      BNB_PRIVATE_KEY: /etc/pantos/bnb-data/keystore
      ETHEREUM_PRIVATE_KEY: /etc/pantos/eth-data/keystore
      PANTOS_STATUS_MONITOR: 1
    ports:
      - 556${INSTANCE-0}:5555
    volumes:
      - type: volume
        source: bnb-data
        target: /etc/pantos/bnb-data
        read_only: true
      - type: volume
        source: eth-data
        target: /etc/pantos/eth-data
        read_only: true
      - type: bind
        source: ./validator-node-config.docker.env
        target: /etc/pantos/validator-node-config.env
        read_only: true
    develop:
      watch:
        - action: sync+restart
          path: validator-node-config.docker.env
          target: /root/validator-node-config.docker.env

volumes:
  bnb-data:
    name: bnb-data-${STACK_IDENTIFIER}-${ETHEREUM_NETWORK-1}
    external: true
  eth-data:
    name: eth-data-${STACK_IDENTIFIER}-${ETHEREUM_NETWORK-1}
    external: true
